"""empty message

Revision ID: 086cef69a851
Revises: f78b8a0bd580
Create Date: 2025-05-11 11:38:17.715935

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "086cef69a851"
down_revision: Union[str, None] = "f78b8a0bd580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birthdate", sa.Date(), nullable=False))
    op.drop_column("users", "birthday")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "birthdate")
    # ### end Alembic commands ###
