"""Edit many to many relationships.

Revision ID: 3f88f1361316
Revises: 5c0e96015cad
Create Date: 2025-05-11 11:21:50.485185

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f88f1361316"
down_revision: Union[str, None] = "5c0e96015cad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_interest",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("interest_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interest_id"],
            ["interests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.drop_index("ix_user_interests_id", table_name="user_interests")
    op.drop_table("user_interests")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_interests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("interest_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["interests.id"], name="user_interests_interest_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_interests_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "id", "user_id", "interest_id", name="user_interests_pkey"
        ),
    )
    op.create_index("ix_user_interests_id", "user_interests", ["id"], unique=False)
    op.drop_table("user_interest")
    # ### end Alembic commands ###
