"""Set unique constraint on name column.

Revision ID: a8f913de66d7
Revises: cba473cefac0
Create Date: 2025-05-04 22:35:14.748842

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8f913de66d7"
down_revision: Union[str, None] = "cba473cefac0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "interests", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "interests", type_="unique")
    # ### end Alembic commands ###
